<?php

/*
|--------------------------------------------------------------------------
| CodeDNA application settings
|--------------------------------------------------------------------------
|
| Application-specific configuration. Application code reads these values
| through config('codedna.*'); env() is only ever called in config files.
|
*/

return [

    // Identifier reported by GET /api/v1/health.
    'service' => 'codedna-api',

    // Deployed build identifier (e.g. a release tag or git SHA), set by the
    // deployment. "dev" for local development.
    'version' => env('APP_VERSION', 'dev'),

    // Current public API version (routes are served under /api/{api_version}).
    'api_version' => 'v1',

    // Proxies whose X-Forwarded-* headers are trusted. Locally, Nginx reaches
    // PHP-FPM over the private Docker network. Comma-separated IPs/CIDRs.
    'trusted_proxies' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('TRUSTED_PROXIES', '10.0.0.0/8,172.16.0.0/12,192.168.0.0/16')),
    ))),

    // Uploaded source archives (docs/architecture/data-flow.md#source-upload).
    'sources' => [
        // Filesystem disk (config/filesystems.php) that stores archives.
        'disk' => 'sources',
        // Optional key prefix inside the bucket (e.g. "phpunit/" for tests).
        // Object keys are always generated by the server:
        // {prefix}projects/{project_id}/snapshots/{snapshot_id}/source.zip
        'key_prefix' => (string) env('SOURCE_STORAGE_PREFIX', ''),
        // Archive limits, enforced before anything is stored. The upload
        // limit must stay below PHP's upload_max_filesize (52M) and Nginx's
        // client_max_body_size (55m).
        'limits' => [
            'archive_bytes' => (int) env('SOURCE_MAX_ARCHIVE_BYTES', 50 * 1024 * 1024),
            'uncompressed_bytes' => (int) env('SOURCE_MAX_UNCOMPRESSED_BYTES', 200 * 1024 * 1024),
            'files' => (int) env('SOURCE_MAX_FILES', 20000),
            'single_file_bytes' => (int) env('SOURCE_MAX_SINGLE_FILE_BYTES', 25 * 1024 * 1024),
            'path_length' => (int) env('SOURCE_MAX_PATH_LENGTH', 512),
        ],
    ],

    // Request rate limits (see docs/api/README.md#rate-limiting).
    /*
    | Internal analyzer (docs/api/internal-analyzer-contract.md) and the
    | analysis pipeline (docs/architecture/data-flow.md). The URL comes only
    | from configuration, never from a request. Timeouts must keep
    | hard_timeout < http timeout < job timeout < queue retry_after
    | (validated at boot by App\Support\ConfigurationValidator).
    */
    'analyzer' => [
        'url' => rtrim((string) env('ANALYZER_URL', 'http://analyzer:8000'), '/'),
        'hmac_secret' => (string) env('ANALYZER_HMAC_SECRET', ''),
        // Accepted for response verification during secret rotation only.
        'hmac_secret_previous' => (string) env('ANALYZER_HMAC_SECRET_PREVIOUS', ''),
        // Largest |now - X-CodeDNA-Timestamp| accepted on analyzer responses.
        'max_skew_seconds' => 300,
        'connect_timeout_seconds' => (int) env('ANALYZER_CONNECT_TIMEOUT_SECONDS', 5),
        'timeout_seconds' => (int) env('ANALYZER_TIMEOUT_SECONDS', 300),
        // The analyzer's own hard limit per request (same variable as the analyzer).
        'hard_timeout_seconds' => (int) env('ANALYZER_HARD_TIMEOUT_SECONDS', 240),
        // Attempts per run (first try included) for retryable failures, and the
        // delay before each retry; an analyzer Retry-After is honoured if longer.
        'max_attempts' => (int) env('ANALYZER_MAX_ATTEMPTS', 3),
        'backoff_seconds' => [30, 120],
        // Lifetime of the pre-signed source URL generated for each attempt.
        'source_url_ttl_seconds' => (int) env('SOURCE_URL_TTL_SECONDS', 900),
        // JSON Schemas of the analyzer responses (packages/api-contracts/analyzer/v1).
        'contracts_path' => (string) env('ANALYZER_CONTRACTS_PATH', '/var/www/contracts/analyzer/v1'),
    ],

    'analysis' => [
        // Dedicated queue connection and queue (config/queue.php "analysis").
        'queue_connection' => 'analysis',
        'queue' => 'analysis',
        // Worker-side limit for one job attempt; must exceed the HTTP timeout.
        'job_timeout_seconds' => (int) env('ANALYSIS_JOB_TIMEOUT_SECONDS', 330),
        // A RUNNING run untouched for this long is failed by analysis:fail-stale
        // (all attempts with their backoff, plus a grace period).
        'stale_after_seconds' => (int) env('ANALYSIS_STALE_AFTER_SECONDS', 1500),
        // A QUEUED run never picked up for this long is failed as stale too.
        'queued_stale_after_seconds' => (int) env('ANALYSIS_QUEUED_STALE_AFTER_SECONDS', 86400),
    ],

    /*
    | CodeDNA scoring (docs/architecture/dna-scoring-v1.md). The version
    | selects a definition in App\Services\Dna\ScoringSpecification; new DNA
    | snapshots are computed with it. Changing it never alters existing
    | snapshots: each (analysis run, scoring version) is scored once.
    */
    'scoring' => [
        'version' => (string) env('CODEDNA_SCORING_VERSION', '1.0.0'),
    ],

    /*
    | Competency matrix (docs/architecture/competency-matrix-v1.md). The version
    | selects a definition in App\Services\Competency\CompetencySpecification;
    | each (DNA snapshot, competency version) is assessed once.
    */
    'competency' => [
        'version' => (string) env('CODEDNA_COMPETENCY_VERSION', '1.0.0'),
    ],

    'rate_limits' => [
        // Every /api/v1 route, per authenticated user or per IP.
        'api_per_minute' => 120,
        // POST /api/v1/auth/login, per email+IP pair and per IP.
        'login_per_minute_per_email' => 5,
        'login_per_minute_per_ip' => 20,
        // POST /api/v1/auth/register, per IP.
        'register_per_minute_per_ip' => 10,
        // PATCH /api/v1/profile, per user.
        'profile_update_per_minute' => 30,
        // PATCH /api/v1/auth/password, per user (limits current-password guessing).
        'password_change_per_minute' => 5,
        'password_change_per_hour' => 20,
        // POST /api/v1/projects, per user.
        'project_create_per_minute' => 10,
        // PATCH /api/v1/projects/{project} and POST .../archive, per user.
        'project_update_per_minute' => 30,
        // POST /api/v1/projects/{project}/source-snapshots, per user.
        'source_upload_per_minute' => 5,
        'source_upload_per_hour' => 60,
        'analysis_create_per_minute' => 10,
    ],

];
