<?php

/*
|--------------------------------------------------------------------------
| CodeDNA application settings
|--------------------------------------------------------------------------
|
| Application-specific configuration. Application code reads these values
| through config('codedna.*'); env() is only ever called in config files.
|
*/

return [

    // Identifier reported by GET /api/v1/health.
    'service' => 'codedna-api',

    // Deployed build identifier (e.g. a release tag or git SHA), set by the
    // deployment. "dev" for local development.
    'version' => env('APP_VERSION', 'dev'),

    // Current public API version (routes are served under /api/{api_version}).
    'api_version' => 'v1',

    // Proxies whose X-Forwarded-* headers are trusted. Locally, Nginx reaches
    // PHP-FPM over the private Docker network. Comma-separated IPs/CIDRs.
    'trusted_proxies' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('TRUSTED_PROXIES', '10.0.0.0/8,172.16.0.0/12,192.168.0.0/16')),
    ))),

    // Uploaded source archives (docs/architecture/data-flow.md#source-upload).
    'sources' => [
        // Filesystem disk (config/filesystems.php) that stores archives.
        'disk' => 'sources',
        // Optional key prefix inside the bucket (e.g. "phpunit/" for tests).
        // Object keys are always generated by the server:
        // {prefix}projects/{project_id}/snapshots/{snapshot_id}/source.zip
        'key_prefix' => (string) env('SOURCE_STORAGE_PREFIX', ''),
        // Archive limits, enforced before anything is stored. The upload
        // limit must stay below PHP's upload_max_filesize (52M) and Nginx's
        // client_max_body_size (55m).
        'limits' => [
            'archive_bytes' => (int) env('SOURCE_MAX_ARCHIVE_BYTES', 50 * 1024 * 1024),
            'uncompressed_bytes' => (int) env('SOURCE_MAX_UNCOMPRESSED_BYTES', 200 * 1024 * 1024),
            'files' => (int) env('SOURCE_MAX_FILES', 20000),
            'single_file_bytes' => (int) env('SOURCE_MAX_SINGLE_FILE_BYTES', 25 * 1024 * 1024),
            'path_length' => (int) env('SOURCE_MAX_PATH_LENGTH', 512),
        ],
    ],

    // Request rate limits (see docs/api/README.md#rate-limiting).
    /*
    | Internal analyzer (docs/api/internal-analyzer-contract.md) and the
    | analysis pipeline (docs/architecture/data-flow.md). The URL comes only
    | from configuration, never from a request. Timeouts must keep
    | hard_timeout < http timeout < job timeout < queue retry_after
    | (validated at boot by App\Support\ConfigurationValidator).
    */
    'analyzer' => [
        'url' => rtrim((string) env('ANALYZER_URL', 'http://analyzer:8000'), '/'),
        'hmac_secret' => (string) env('ANALYZER_HMAC_SECRET', ''),
        // Accepted for response verification during secret rotation only.
        'hmac_secret_previous' => (string) env('ANALYZER_HMAC_SECRET_PREVIOUS', ''),
        // Largest |now - X-CodeDNA-Timestamp| accepted on analyzer responses.
        'max_skew_seconds' => 300,
        'connect_timeout_seconds' => (int) env('ANALYZER_CONNECT_TIMEOUT_SECONDS', 5),
        'timeout_seconds' => (int) env('ANALYZER_TIMEOUT_SECONDS', 300),
        // The analyzer's own hard limit per request (same variable as the analyzer).
        'hard_timeout_seconds' => (int) env('ANALYZER_HARD_TIMEOUT_SECONDS', 240),
        // Attempts per run (first try included) for retryable failures, and the
        // delay before each retry; an analyzer Retry-After is honoured if longer.
        'max_attempts' => (int) env('ANALYZER_MAX_ATTEMPTS', 3),
        'backoff_seconds' => [30, 120],
        // Phase 26 (docs/performance/queue-performance.md#analyzer-slots): the
        // analyzer runs at most this many analyses at once (same variable as
        // the analyzer) and answers more with ANALYZER_BUSY. Workers take one
        // of these slots (a Redis semaphore) before calling it, so extra
        // workers wait instead of spending attempts on BUSY answers.
        'max_concurrency' => (int) env('ANALYZER_MAX_CONCURRENCY', 2),
        // How long a worker waits for a slot before handing the run to a
        // fresh, delayed job (no attempt is used). ANALYZER_TIMEOUT_SECONDS
        // plus this must stay below ANALYSIS_JOB_TIMEOUT_SECONDS.
        'slot_wait_seconds' => (int) env('ANALYZER_SLOT_WAIT_SECONDS', 20),
        // Lifetime of the pre-signed source URL generated for each attempt.
        'source_url_ttl_seconds' => (int) env('SOURCE_URL_TTL_SECONDS', 900),
        // JSON Schemas of the analyzer responses (packages/api-contracts/analyzer/v1).
        'contracts_path' => (string) env('ANALYZER_CONTRACTS_PATH', '/var/www/contracts/analyzer/v1'),
    ],

    'analysis' => [
        // Dedicated queue connection and queue (config/queue.php "analysis").
        'queue_connection' => 'analysis',
        'queue' => 'analysis',
        // Worker-side limit for one job attempt; must exceed the HTTP timeout.
        'job_timeout_seconds' => (int) env('ANALYSIS_JOB_TIMEOUT_SECONDS', 330),
        // A RUNNING run untouched for this long is failed by analysis:fail-stale
        // (all attempts with their backoff, plus a grace period).
        'stale_after_seconds' => (int) env('ANALYSIS_STALE_AFTER_SECONDS', 1500),
        // A QUEUED run never picked up for this long is failed as stale too.
        'queued_stale_after_seconds' => (int) env('ANALYSIS_QUEUED_STALE_AFTER_SECONDS', 86400),
    ],

    /*
    | CodeDNA scoring (docs/architecture/dna-scoring-v1.md). The version
    | selects a definition in App\Services\Dna\ScoringSpecification; new DNA
    | snapshots are computed with it. Changing it never alters existing
    | snapshots: each (analysis run, scoring version) is scored once.
    */
    'scoring' => [
        'version' => (string) env('CODEDNA_SCORING_VERSION', '1.0.0'),
    ],

    /*
    | Competency matrix (docs/architecture/competency-matrix-v1.md). The version
    | selects a definition in App\Services\Competency\CompetencySpecification;
    | each (DNA snapshot, competency version) is assessed once.
    */
    'competency' => [
        'version' => (string) env('CODEDNA_COMPETENCY_VERSION', '1.0.0'),
    ],

    /*
    | Skill gap analysis (docs/architecture/skill-gap-v1.md). The version
    | selects a definition, including its target profile, in
    | App\Services\SkillGap\SkillGapSpecification.
    */
    'skill_gap' => [
        'version' => (string) env('CODEDNA_SKILL_GAP_VERSION', '1.0.0'),
    ],

    /*
    | Learning roadmaps (docs/architecture/learning-roadmap-v1.md). A planning
    | layer: generated deterministically from a skill gap snapshot, never by
    | AI, and never changing CodeDNA, competencies or skill gaps. The catalog
    | version selects the server-owned tracks, the rules version the
    | selection and ordering rules.
    */
    /*
    | Growth tracking (docs/architecture/growth-tracking-v1.md). An
    | observation layer: compares each new deterministic assessment with the
    | project's preceding one, reading stored scores only. Never a score of
    | its own, never AI, and never fed by learning activity.
    */
    'growth' => [
        'rules_version' => (string) env('CODEDNA_GROWTH_RULES_VERSION', '1.0.0'),
    ],

    'roadmap' => [
        'catalog_version' => (string) env('CODEDNA_ROADMAP_VERSION', '1.0.0'),
        'rules_version' => (string) env('CODEDNA_ROADMAP_RULES_VERSION', '1.0.0'),
    ],

    /*
    | AI assessment and interpretation (docs/architecture/ai-assessment-v1.md)
    | and the local AI intelligence layer (Phase 29,
    | docs/architecture/ai-intelligence-v1.md). Non-authoritative: the AI
    | explains stored deterministic results and never changes them. Disabled
    | by default; generation runs only when a user requests it, on its own
    | queue. The default provider is a local Ollama server; nothing ever falls
    | back to another provider. The provider, model, URL and key come only
    | from the environment; the key is never stored, logged or sent to the
    | frontend. Timeouts must keep slot wait + timeout < job timeout < queue
    | retry_after (validated at boot).
    */
    'ai' => [
        'enabled' => (bool) env('AI_ENABLED', false),
        // "ollama" (a local Ollama server, native API), "openai_compatible"
        // (any Chat Completions endpoint) or "fake" (deterministic template,
        // never allowed in production).
        'provider' => (string) env('AI_PROVIDER', 'ollama'),
        'model' => (string) env('AI_MODEL', 'qwen2.5-coder:7b'),
        'base_url' => rtrim((string) env('AI_BASE_URL', 'http://ollama:11434'), '/'),
        'api_key' => (string) env('AI_API_KEY', ''),
        // A provider outside the private network (a host name with a dot or an
        // IP address) is a separate trust boundary: in production it needs
        // https and this explicit opt-in (docs/operations/local-ai.md).
        'allow_remote_endpoint' => (bool) env('AI_ALLOW_REMOTE_ENDPOINT', false),
        // "json_schema" (strict structured output), "json_object" or "none",
        // for servers without structured output support. Ollama always
        // receives the JSON schema as its "format".
        'structured_output' => (string) env('AI_STRUCTURED_OUTPUT', 'json_schema'),
        'connect_timeout_seconds' => (int) env('AI_CONNECT_TIMEOUT_SECONDS', 5),
        'timeout_seconds' => (int) env('AI_TIMEOUT_SECONDS', 120),
        // Bounds on what is sent and accepted (bytes of canonical input JSON,
        // bytes of response content, and the max_tokens / num_predict sent).
        'max_input_bytes' => (int) env('AI_MAX_INPUT_BYTES', 32768),
        'max_output_bytes' => (int) env('AI_MAX_OUTPUT_BYTES', 16384),
        'max_output_tokens' => (int) env('AI_MAX_OUTPUT_TOKENS', 2000),
        // The model's context window (Ollama num_ctx). A request whose
        // estimated prompt tokens plus max_output_tokens exceed it is refused
        // before it is sent, never truncated.
        'context_tokens' => (int) env('AI_CONTEXT_TOKENS', 8192),
        // Generations at once, across every worker (a Redis semaphore), and how
        // long a job waits for one before it is retried later.
        'max_concurrency' => (int) env('AI_MAX_CONCURRENCY', 1),
        'slot_wait_seconds' => (int) env('AI_SLOT_WAIT_SECONDS', 10),
        // How long Ollama keeps the model loaded after a request.
        'keep_alive' => (string) env('AI_KEEP_ALIVE', '5m'),
        // How long a connectivity / model availability check is cached.
        'health_cache_seconds' => (int) env('AI_HEALTH_CACHE_SECONDS', 60),
        // Provider calls per assessment or insight (first included), for
        // timeouts, 429 and 5xx only, with the delay before each retry
        // (Retry-After honoured if longer, up to the last value). Invalid
        // output is never retried.
        'max_attempts' => (int) env('AI_MAX_ATTEMPTS', 3),
        'backoff_seconds' => [20, 60],
        'job_timeout_seconds' => (int) env('AI_JOB_TIMEOUT_SECONDS', 180),
        // QUEUED or RUNNING assessments and insights untouched for this long
        // are failed by assessment:fail-stale / insight:fail-stale.
        'stale_after_seconds' => (int) env('AI_STALE_AFTER_SECONDS', 900),
        'queued_stale_after_seconds' => (int) env('AI_QUEUED_STALE_AFTER_SECONDS', 3600),
        'queue_connection' => 'analysis',
        'queue' => 'assessment',
        'version' => (string) env('CODEDNA_ASSESSMENT_VERSION', '1.0.0'),
        // Evidence-grounded insights (Phase 29): growth, learning roadmap and
        // challenge feedback interpretations.
        'insights_version' => (string) env('CODEDNA_INSIGHTS_VERSION', '1.0.0'),
    ],

    /*
    | Coding challenges (docs/architecture/coding-challenges-v1.md). A
    | practice layer: challenges never change CodeDNA, competencies or skill
    | gaps, and they never use AI. Submitted code runs only in the isolated
    | evaluator service (docs/architecture/challenge-evaluator.md), reached
    | through the spool volume; "none" disables execution (submissions are
    | refused) and nothing ever falls back to running code anywhere else.
    | Timeouts keep wait < job timeout < queue retry_after (validated at boot).
    */
    'challenges' => [
        'enabled' => (bool) env('CHALLENGE_ENABLED', true),
        'catalog_version' => (string) env('CODEDNA_CHALLENGE_CATALOG_VERSION', '1.0.0'),
        // "spool" (the evaluator service) or "none".
        'evaluator' => (string) env('CHALLENGE_EVALUATOR', 'none'),
        'spool_path' => (string) env('CHALLENGE_EVALUATOR_SPOOL', '/var/spool/codedna-challenges'),
        // How long one job waits for the evaluator's result, and how old the
        // evaluator's heartbeat may be before it counts as unavailable.
        'wait_seconds' => (int) env('CHALLENGE_EVALUATOR_WAIT_SECONDS', 45),
        'heartbeat_max_age_seconds' => 30,
        // The weakest runtime isolation the evaluator may attest before code
        // is submitted to it (Phase 25): "container" (development) or
        // "gvisor" (required wherever the application is deployed).
        'required_isolation' => (string) env('CHALLENGE_EVALUATOR_ISOLATION', 'container'),
        // Submission limits, enforced before anything is stored or evaluated.
        'max_source_bytes' => (int) env('CHALLENGE_MAX_SOURCE_BYTES', 16384),
        'max_source_lines' => (int) env('CHALLENGE_MAX_SOURCE_LINES', 400),
        // Graded attempts per challenge (evaluation errors do not count).
        'max_attempts' => (int) env('CHALLENGE_MAX_ATTEMPTS', 5),
        // Evaluation jobs: attempts (transient evaluator failures only) and
        // the delay before each retry. A retry never re-executes a submission.
        'max_job_attempts' => 3,
        'backoff_seconds' => [10, 30],
        'job_timeout_seconds' => (int) env('CHALLENGE_JOB_TIMEOUT_SECONDS', 90),
        'stale_after_seconds' => 600,
        'queued_stale_after_seconds' => 3600,
        'queue_connection' => 'analysis',
        'queue' => 'challenge',
    ],

    /*
    | GitHub integration (Phase 19, docs/architecture/github-integration-v1.md).
    | A GitHub App with read-only Contents and Metadata permissions. GitHub is
    | a source provider only: an import becomes an immutable source snapshot,
    | analyzed by the existing pipeline. Every URL comes from configuration,
    | never from a request. The integration is off unless all of app_id,
    | app_slug, client_id, client_secret and the private key are set.
    */
    'github' => [
        'app_id' => (string) env('GITHUB_APP_ID', ''),
        'app_slug' => (string) env('GITHUB_APP_SLUG', ''),
        'client_id' => (string) env('GITHUB_APP_CLIENT_ID', ''),
        'client_secret' => (string) env('GITHUB_APP_CLIENT_SECRET', ''),
        // PEM text (newlines may be written as \n) or a path to the PEM file. Never committed.
        'private_key' => (string) env('GITHUB_APP_PRIVATE_KEY', ''),
        'private_key_path' => (string) env('GITHUB_APP_PRIVATE_KEY_PATH', ''),
        // Official endpoints; overridable only for a local test double.
        'api_url' => (string) env('GITHUB_API_URL', 'https://api.github.com'),
        'web_url' => (string) env('GITHUB_WEB_URL', 'https://github.com'),
        // Origins a repository archive download may be redirected to.
        'archive_origins' => array_values(array_filter(array_map('trim', explode(',', (string) env('GITHUB_ARCHIVE_ORIGINS', 'https://codeload.github.com'))))),
        // Where GitHub sends the browser back to (a frontend page that completes the flow).
        'callback_url' => (string) env('GITHUB_CALLBACK_URL', rtrim((string) env('APP_URL', 'http://localhost'), '/').'/app/github/callback'),
        'state_ttl_seconds' => (int) env('GITHUB_STATE_TTL_SECONDS', 600),
        'connect_timeout_seconds' => (int) env('GITHUB_CONNECT_TIMEOUT_SECONDS', 5),
        'timeout_seconds' => (int) env('GITHUB_TIMEOUT_SECONDS', 15),
        'download_timeout_seconds' => (int) env('GITHUB_DOWNLOAD_TIMEOUT_SECONDS', 120),
        // Largest JSON response read from GitHub; anything larger is refused.
        'max_response_bytes' => (int) env('GITHUB_MAX_RESPONSE_BYTES', 4 * 1024 * 1024),
        // One retry of an idempotent GET after a 502/503/504 or a connection failure.
        'retry_delay_ms' => (int) env('GITHUB_RETRY_DELAY_MS', 250),
        'queue_connection' => 'analysis',
        'queue' => 'github',
        'job_timeout_seconds' => (int) env('GITHUB_IMPORT_JOB_TIMEOUT_SECONDS', 180),
        // A QUEUED or RUNNING import untouched for this long no longer blocks a new one.
        'import_stale_after_seconds' => (int) env('GITHUB_IMPORT_STALE_AFTER_SECONDS', 900),
    ],

    /*
    |--------------------------------------------------------------------------
    | GitLab and Bitbucket Cloud (Phase 28)
    |--------------------------------------------------------------------------
    |
    | docs/integrations/provider-architecture.md. OAuth 2.0 repository
    | providers: each is off until its client ID and secret are set. Imports
    | share the GitHub import queue, timeouts and the GitHub import quota.
    | URLs are fixed per provider (or, for GitLab, one administrator-set base
    | URL); nothing a client sends ever becomes a request destination.
    |
    */
    'repository_providers' => [
        'gitlab' => [
            'client_id' => (string) env('GITLAB_CLIENT_ID', ''),
            'client_secret' => (string) env('GITLAB_CLIENT_SECRET', ''),
            // GitLab.com by default; a self-managed GitLab by its exact origin
            // (https in production). OAuth, API and archives all use it.
            'base_url' => rtrim((string) env('GITLAB_BASE_URL', 'https://gitlab.com'), '/'),
            'callback_url' => (string) env('GITLAB_CALLBACK_URL', rtrim((string) env('APP_URL', 'http://localhost'), '/').'/app/integrations/gitlab/callback'),
            // read_api: read-only API access (projects, branches, archives); nothing is written.
            'scopes' => 'read_api',
        ],
        'bitbucket' => [
            'client_id' => (string) env('BITBUCKET_CLIENT_ID', ''),
            'client_secret' => (string) env('BITBUCKET_CLIENT_SECRET', ''),
            // Bitbucket Cloud only (Data Center is not supported). Official
            // endpoints; overridable only for a local test double.
            'api_url' => rtrim((string) env('BITBUCKET_API_URL', 'https://api.bitbucket.org'), '/'),
            'web_url' => rtrim((string) env('BITBUCKET_WEB_URL', 'https://bitbucket.org'), '/'),
            // Origins an archive download may be redirected to (exact origins).
            'archive_origins' => array_values(array_filter(array_map('trim', explode(',', (string) env('BITBUCKET_ARCHIVE_ORIGINS', 'https://bitbucket.org'))))),
            'callback_url' => (string) env('BITBUCKET_CALLBACK_URL', rtrim((string) env('APP_URL', 'http://localhost'), '/').'/app/integrations/bitbucket/callback'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Billing (Phase 23)
    |--------------------------------------------------------------------------
    |
    | docs/billing/billing-architecture.md. Plans, prices, features and quotas
    | are NOT configuration: they are the frozen, versioned catalog in code
    | (App\Services\Billing\Catalog), stored as immutable rows. Nothing here
    | can grant a plan or raise a quota.
    |
    | provider: "none" (default: no payment provider; every user is on FREE)
    | or "fake" (a signed, deterministic test provider; refused outside the
    | local and testing environments).
    |
    */
    'billing' => [
        'provider' => (string) env('BILLING_PROVIDER', 'none'),
        // The webhook signing secret of the configured provider. Never committed.
        'webhook_secret' => (string) env('BILLING_WEBHOOK_SECRET', ''),
        // A webhook signed further than this from now is refused (replay protection).
        'webhook_tolerance_seconds' => 300,
        // Largest webhook body read; providers send a few KiB.
        'webhook_max_bytes' => 65536,
    ],

    /*
    |--------------------------------------------------------------------------
    | Enterprise edition (Phase 27)
    |--------------------------------------------------------------------------
    |
    | docs/enterprise/licensing.md. Without a license (the default) the
    | installation is the Community edition and nothing changes. A license is
    | a signed file mounted read-only (CODEDNA_LICENSE_PATH); it is verified
    | offline against the public keys in config/license.php, never against a
    | key from the environment. An absent or invalid license grants nothing.
    |
    */
    'enterprise' => [
        // Absolute path of the license file; empty = no license. An empty
        // file at the path also means no license (the production default
        // mounts /dev/null).
        'license_path' => (string) env('CODEDNA_LICENSE_PATH', ''),
        // Licenses are a few hundred bytes; anything larger is refused unread.
        'license_max_bytes' => 16384,
    ],

    /*
    |--------------------------------------------------------------------------
    | Self-service registration (Phase 27)
    |--------------------------------------------------------------------------
    |
    | docs/enterprise/configuration-reference.md#registration. "open" (the
    | default: anyone may create an account), "restricted" (only email
    | addresses in REGISTRATION_ALLOWED_EMAIL_DOMAINS) or "closed" (no new
    | accounts; existing accounts keep working). A security setting, in every
    | edition.
    |
    */
    'registration' => [
        'mode' => (string) env('REGISTRATION_MODE', 'open'),
        'allowed_email_domains' => array_values(array_filter(array_map(
            static fn (string $domain): string => strtolower(trim($domain)),
            explode(',', (string) env('REGISTRATION_ALLOWED_EMAIL_DOMAINS', '')),
        ), static fn (string $domain): bool => $domain !== '')),
    ],

    'rate_limits' => [
        // Every /api/v1 route, per authenticated user or per IP.
        'api_per_minute' => 120,
        // GET /api/v1/me, the session check of every page render (Phase 30),
        // per user or IP; outside the api budget above.
        'session_per_minute' => 300,
        // POST /api/v1/auth/login, per email+IP pair and per IP, and per
        // email across all IPs (Phase 21: a distributed guesser is still
        // bounded per account).
        'login_per_minute_per_email' => 5,
        'login_per_minute_per_ip' => 20,
        'login_per_hour_per_email' => 30,
        // POST /api/v1/auth/register, per IP.
        'register_per_minute_per_ip' => 10,
        // PATCH /api/v1/profile, per user.
        'profile_update_per_minute' => 30,
        // PATCH /api/v1/auth/password, per user (limits current-password guessing).
        'password_change_per_minute' => 5,
        'password_change_per_hour' => 20,
        // POST /api/v1/projects, per user.
        'project_create_per_minute' => 10,
        // PATCH /api/v1/projects/{project} and POST .../archive, per user.
        'project_update_per_minute' => 30,
        // POST /api/v1/projects/{project}/source-snapshots, per user.
        'source_upload_per_minute' => 5,
        'source_upload_per_hour' => 60,
        'analysis_create_per_minute' => 10,
        // POST /api/v1/projects/{project}/assessments, per user (provider calls cost money).
        'assessment_create_per_minute' => 5,
        'assessment_create_per_hour' => 30,
        // POST .../challenges and POST .../challenges/{challenge}/submissions, per user.
        'challenge_assign_per_minute' => 10,
        'challenge_submit_per_minute' => 10,
        'challenge_submit_per_hour' => 60,
        // POST .../roadmaps and POST .../roadmaps/{roadmap}/steps/{step}/complete, per user.
        'roadmap_generate_per_minute' => 10,
        'roadmap_progress_per_minute' => 60,
        // GitHub (Phase 19), per user: starting authorization, browsing
        // installations, repositories and branches, changing a connection,
        // and imports (each downloads a whole archive).
        'github_authorize_per_minute' => 10,
        'github_read_per_minute' => 60,
        'github_write_per_minute' => 20,
        'github_import_per_minute' => 5,
        'github_import_per_hour' => 30,
        // Organizations (Phase 24), per user unless noted: creating
        // organizations, changing them and their members, inviting, and
        // invitation links (accept per user and per IP; the unauthenticated
        // preview per IP), which bounds token guessing.
        'organization_create_per_minute' => 5,
        'organization_create_per_hour' => 20,
        'organization_write_per_minute' => 30,
        'invitation_create_per_minute' => 10,
        'invitation_create_per_hour' => 50,
        'invitation_accept_per_minute' => 10,
        'invitation_accept_per_minute_per_ip' => 20,
        'invitation_preview_per_minute_per_ip' => 30,
        // GET /api/v1/billing/*, per user.
        'billing_read_per_minute' => 60,
        // POST /api/v1/billing/webhooks/{provider}, per provider and IP. Generous:
        // providers retry and burst, and a refused delivery is retried later anyway.
        'billing_webhook_per_minute' => 600,
    ],

];
