<?php

declare(strict_types=1);

namespace Tests\Support;

/**
 * Small archives produced by real tools, base64-encoded. Each contains the
 * same three text files (src/app/main.php, src/app/tool.py, src/README.md);
 * nothing in them is ever extracted or executed. They prove the inspector
 * accepts what common writers produce, not only what ZipBuilder writes.
 *
 * Regenerate with the commands in docs/architecture/data-flow.md#source-upload
 * if the inspector's accepted format ever changes.
 */
final class RealWorldZips
{
    /** Python 3.11 zipfile, deflated, with directory entries. */
    public const PYTHON_ZIPFILE = 'UEsDBBQAAAAAANYORl0AAAAAAAAAAAAAAAAEAAAAc3JjL1BLAwQUAAAAAADWDkZdAAAAAAAAAAAAAAAACAAAAHNyYy9hcHAvUEsD'
        .'BBQAAAAIANYORl26vIR8FgAAABQAAAAQAAAAc3JjL2FwcC9tYWluLnBocLOxL8go4EpNzshXUMpIzcnJV7LmAgBQSwMEFAAAAAgA'
        .'1g5GXff1mK4OAAAADAAAAA8AAABzcmMvYXBwL3Rvb2wucHkrKMrMK9FQyshU0uQCAFBLAwQUAAAACADWDkZd9MahhwkAAAAHAAAA'
        .'DQAAAHNyYy9SRUFETUUubWRTVnBJzc3nAgBQSwECFAMUAAAAAADWDkZdAAAAAAAAAAAAAAAABAAAAAAAAAAAABAA7UEAAAAAc3Jj'
        .'L1BLAQIUAxQAAAAAANYORl0AAAAAAAAAAAAAAAAIAAAAAAAAAAAAEADtQSIAAABzcmMvYXBwL1BLAQIUAxQAAAAIANYORl26vIR8'
        .'FgAAABQAAAAQAAAAAAAAAAAAAACkgUgAAABzcmMvYXBwL21haW4ucGhwUEsBAhQDFAAAAAgA1g5GXff1mK4OAAAADAAAAA8AAAAA'
        .'AAAAAAAAAKSBjAAAAHNyYy9hcHAvdG9vbC5weVBLAQIUAxQAAAAIANYORl30xqGHCQAAAAcAAAANAAAAAAAAAAAAAACkgccAAABz'
        .'cmMvUkVBRE1FLm1kUEsFBgAAAAAFAAUAHgEAAPsAAAAAAA==';

    /** Python 3.11 zipfile written to a non-seekable stream (data descriptors). */
    public const PYTHON_STREAMING = 'UEsDBBQACAAIAAAAIQAAAAAAAAAAAAAAAAAQAAAAc3JjL2FwcC9tYWluLnBocLOxL8go4EpNzshXUMpIzcnJV7LmAgBQSwcIuryE'
        .'fBYAAAAUAAAAUEsDBBQACAAIAAAAIQAAAAAAAAAAAAAAAAAPAAAAc3JjL2FwcC90b29sLnB5KyjKzCvRUMrIVNLkAgBQSwcI9/WY'
        .'rg4AAAAMAAAAUEsDBBQACAAIAAAAIQAAAAAAAAAAAAAAAAANAAAAc3JjL1JFQURNRS5tZFNWcEnNzecCAFBLBwj0xqGHCQAAAAcA'
        .'AABQSwECFAMUAAgACAAAACEAuryEfBYAAAAUAAAAEAAAAAAAAAAAAAAAgAEAAAAAc3JjL2FwcC9tYWluLnBocFBLAQIUAxQACAAI'
        .'AAAAIQD39ZiuDgAAAAwAAAAPAAAAAAAAAAAAAACAAVQAAABzcmMvYXBwL3Rvb2wucHlQSwECFAMUAAgACAAAACEA9MahhwkAAAAH'
        .'AAAADQAAAAAAAAAAAAAAgAGfAAAAc3JjL1JFQURNRS5tZFBLBQYAAAAAAwADALYAAADjAAAAAAA=';

    /** Info-ZIP 3.0 `zip -r` (Unix extra fields). */
    public const INFO_ZIP = 'UEsDBAoAAAAAANcORl0AAAAAAAAAAAAAAAAEABwAc3JjL1VUCQAD5VTEauVUxGp1eAsAAQQAAAAABAAAAABQSwMECgAAAAAA1w5G'
        .'XQAAAAAAAAAAAAAAAAgAHABzcmMvYXBwL1VUCQAD5VTEauVUxGp1eAsAAQQAAAAABAAAAABQSwMECgAAAAAA1w5GXbq8hHwUAAAA'
        .'FAAAABAAHABzcmMvYXBwL21haW4ucGhwVVQJAAPlVMRq5VTEanV4CwABBAAAAAAEAAAAADw/cGhwCmVjaG8gImhlbGxvIjsKUEsD'
        .'BAoAAAAAANcORl339ZiuDAAAAAwAAAAPABwAc3JjL2FwcC90b29sLnB5VVQJAAPlVMRq5VTEanV4CwABBAAAAAAEAAAAAHByaW50'
        .'KCJoaSIpClBLAwQKAAAAAADXDkZd9MahhwcAAAAHAAAADQAcAHNyYy9SRUFETUUubWRVVAkAA+VUxGrlVMRqdXgLAAEEAAAAAAQA'
        .'AAAAIyBEZW1vClBLAQIeAwoAAAAAANcORl0AAAAAAAAAAAAAAAAEABgAAAAAAAAAEADtQQAAAABzcmMvVVQFAAPlVMRqdXgLAAEE'
        .'AAAAAAQAAAAAUEsBAh4DCgAAAAAA1w5GXQAAAAAAAAAAAAAAAAgAGAAAAAAAAAAQAO1BPgAAAHNyYy9hcHAvVVQFAAPlVMRqdXgL'
        .'AAEEAAAAAAQAAAAAUEsBAh4DCgAAAAAA1w5GXbq8hHwUAAAAFAAAABAAGAAAAAAAAQAAAKSBgAAAAHNyYy9hcHAvbWFpbi5waHBV'
        .'VAUAA+VUxGp1eAsAAQQAAAAABAAAAABQSwECHgMKAAAAAADXDkZd9/WYrgwAAAAMAAAADwAYAAAAAAABAAAApIHeAAAAc3JjL2Fw'
        .'cC90b29sLnB5VVQFAAPlVMRqdXgLAAEEAAAAAAQAAAAAUEsBAh4DCgAAAAAA1w5GXfTGoYcHAAAABwAAAA0AGAAAAAAAAQAAAKSB'
        .'MwEAAHNyYy9SRUFETUUubWRVVAUAA+VUxGp1eAsAAQQAAAAABAAAAABQSwUGAAAAAAUABQCWAQAAgQEAAAAA';

    /** `git archive --format=zip --prefix=src/` (archive comment). */
    public const GIT_ARCHIVE = 'UEsDBAoAAAAAANYORl0AAAAAAAAAAAAAAAAEAAkAc3JjL1VUBQAB5VTEalBLAwQKAAAAAADWDkZd9MahhwcAAAAHAAAADQAJAHNy'
        .'Yy9SRUFETUUubWRVVAUAAeVUxGojIERlbW8KUEsDBAoAAAAAANYORl0AAAAAAAAAAAAAAAAIAAkAc3JjL2FwcC9VVAUAAeVUxGpQ'
        .'SwMECgAAAAAA1g5GXbq8hHwUAAAAFAAAABAACQBzcmMvYXBwL21haW4ucGhwVVQFAAHlVMRqPD9waHAKZWNobyAiaGVsbG8iOwpQ'
        .'SwMECgAAAAAA1g5GXff1mK4MAAAADAAAAA8ACQBzcmMvYXBwL3Rvb2wucHlVVAUAAeVUxGpwcmludCgiaGkiKQpQSwECAAAKAAAA'
        .'AADWDkZdAAAAAAAAAAAAAAAABAAJAAAAAAAAABAAAAAAAAAAc3JjL1VUBQAB5VTEalBLAQIAAAoAAAAAANYORl30xqGHBwAAAAcA'
        .'AAANAAkAAAAAAAEAAAAAACsAAABzcmMvUkVBRE1FLm1kVVQFAAHlVMRqUEsBAgAACgAAAAAA1g5GXQAAAAAAAAAAAAAAAAgACQAA'
        .'AAAAAAAQAAAAZgAAAHNyYy9hcHAvVVQFAAHlVMRqUEsBAgAACgAAAAAA1g5GXbq8hHwUAAAAFAAAABAACQAAAAAAAQAAAAAAlQAA'
        .'AHNyYy9hcHAvbWFpbi5waHBVVAUAAeVUxGpQSwECAAAKAAAAAADWDkZd9/WYrgwAAAAMAAAADwAJAAAAAAABAAAAAADgAAAAc3Jj'
        .'L2FwcC90b29sLnB5VVQFAAHlVMRqUEsFBgAAAAAFAAUASwEAACIBAAAoAGRkZWRjZGI3YzczMDRmNTkyNWVkNWY0NGUzMjE0NjU3'
        .'ZTQwMzc3N2Y=';

    /**
     * @return array<string, array{0: string}>
     */
    public static function all(): array
    {
        return [
            'python zipfile' => [self::PYTHON_ZIPFILE],
            'python streaming' => [self::PYTHON_STREAMING],
            'info-zip' => [self::INFO_ZIP],
            'git archive' => [self::GIT_ARCHIVE],
        ];
    }

    public static function save(string $base64): string
    {
        $path = (string) tempnam(sys_get_temp_dir(), 'codedna-zip-');
        file_put_contents($path, (string) base64_decode($base64, true));

        return $path;
    }
}
